version: "3.9"

services:
  mysql:
    image: mysql:9.5.0
    container_name: mysql-9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_db
    ports:
      - "3307:3306"
    networks:
      - ticket-network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./target/docker
      dockerfile: Dockerfile
    container_name: ticket-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - ticket-network
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql-9:3306/ticket_db
    #   SPRING_DATASOURCE_USERNAME: root
    #   SPRING_DATASOURCE_PASSWORD: root

networks:
  ticket-network:
    driver: bridge

volumes:
  mysql_data:
